[aliases]
"gnome.*" = "gnome"
"Gnome.*" = "gnome"

[icons]
"ART" = ""
"rawtherapee" = ""
"Rawtherapee" = ""
"Anki" = ""
"gnome-calculator"=""
"Baobab" = "󰋊"
"Bitwarden" = ""
"Blueberry.py" = ""
"Brave-browser" = "󰖟"
"brave-browser" = "󰖟"
"cataclysm" = ""
"Code" = "󰨞"
"Code - Insiders" = "󰨞"
"code-url-handler" = "󰨞"
"cava" = ""
"io.github.celluloid_player.Celluloid" = "󰎁"
"zoom" = ""
"VSCodium" = "󰨞"
"signal" = "󱜺"
"azote" = "󰸉"
"Com.github.tchx84.Flatseal" = ""
"cool-retro-term" = ""
"Chromium" = "󰊯"
"Gnome-terminal" = ""
"seahorse" = "󰌆"
"kitty" = ""
"foot" = ""
"footclient" = ""
"Dconf-editor" = "󰊬"
"Deadbeef" = ""
"DesktopEditors" = "󰏆"
"Microsoft-edge-beta" = ""
"discord" = "󰙯"
"dolphin" = ""
"Droidcam" = ""
"eog" = "󰋩"
"file-roller" = ""
"firefox-aurora" = ""
"Fsearch" = ""
"Gcolor3" = "קּ"
"Zotero" = ""
"Lollypop" = ""
"gimp" = ""
"org.gnome.Nautilus" = ""
"GitHub Desktop" = ""
"Gnome-boxes" = ""
"Gnome-calendar" = ""
"gnome" = "󰊬"
"Pamac-manager" = ""
"Gucharmap" = ""
"Io.github.celluloid_player.Celluloid" = "󰎁"
"java" = ""
"jetbrains-idea" = ""
"jetbrains-pycharm" = ""
"jetbrains-rider" = ""
"jetbrains-studio" = ""
"jetbrains-toolbox" = ""
"jetbrains-webstorm" = ""
"keepassxc" = ""
"KeePassXC" = ""
"foobar2000.exe" = ""
"libreoffice-calc" = "󰏆"
"libreoffice-math" = "󰏆"
"libreoffice-startcenter" = "󰏆"
"libreoffice-writer" = "󰏆"
"Microsoft Teams - Preview" = "󰊻"
"minecraft" = "󰍳"
"Nextcloud" = ""
"Nightly" = ""
"Nm-connection-editor" = ""
"NoiseTorch" = "󰕾"
"okular" = ""
"Org.gnome.Software" = ""
"org.gnome.Software" = ""
"obs" = "壘"
"Pavucontrol" = "墳"
"Postman" = "ﬥ"
"protonmail-bridge" = ""
"org.qbittorrent.qBittorrent" = ""
"Quodlibet" = ""
"resolve" = ""
"retroarch" = "󰺵"
"rhythmbox" = ""
"Google-chrome" = ""
"Signal" = "󰵅"
"Slack" = ""
"yuzu" = "󰊗"
"Lutris" = "󰊗"
"Nitrogen" = "󰸉"
"Evolution" = ""
"Evolution.bin" = ""
"Soffice" = "󰏆"
"SpeedCrunch" = ""
"Spotify" = ""
"Steam" = ""
"strawberry" =""
"thunderbird-nightly" = ""
"Tor Browser" = "󱞐"
"Typora" = ""
"Qemu-system-x86_64" = ""
"vlc" = "󰕼"
"wine" = ""
"Pdfarranger" = ""
"winebottler" = "󰡶"
"wineskin" = "󰡶"
"mpv" = "󰎁"

[general]
separator = " "
# default_icon = "󰆦"

[options]
remove_duplicates = true
no_names = true
no_icon_names = true
